Feature list structure
marilirulita/To-Do-list pull request #1
Opened 2021-09-24 16:51 UTC by marilirulita

This project is built a to-do list adding and managing DOM elements using javascript and Webpack

- First version creates an array of objects which represent the item list
- Create a constructor of list object which represents each element of the tasks list.
- Add a button to future delete elements in the list that are completed.

2021-09-24 18:51 UTC, mikenath223 requested changes
Hello  @marilirulita 

You've done pretty well so far!
But for a few issues, you are almost done with this. Hang in there!


## Required Changes ♻️
_Please check the comments under the review._

Happy coding, Cheers! 🚀🚀

Do feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it is valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-24 18:54 UTC, mikenath223 commented on src/index.html
> +        <div id="list-elem">
- [ ] Kindly make the project match the given design:

| Original | Yours |
| ----- | ------ |
| <img src="https://camo.githubusercontent.com/d04bee7a5b8f62cc6655dbec65c4d14583e4d78d0c434ddc070f6881bb9568fc/68747470733a2f2f696d672e796f75747562652e636f6d2f76692f416355642d5f596a6a71672f302e6a7067" height="250px"/> | <img src="https://user-images.githubusercontent.com/33323077/134726002-dbc3996b-aaff-433e-820a-5df03424d793.png" height="250px"/> |

2021-09-24 18:54 UTC, mikenath223 commented on src/index.js
> +// import _ from 'lodash';
- [ ] Please remove the commented code.

2021-09-24 18:55 UTC, mikenath223 commented on src/index.js
> +}
- [ ] Kindly change these and other regular functions to es6 arrow function syntax following the JavaScript best practices guide.

2021-09-24 18:55 UTC, mikenath223 commented on src/index.js
> +// });
- [ ] Please remove this commented code.

2021-09-27 19:08 UTC, GzimAsani approved these changes
# Hello @marilirulita     

## Thank you for implementing all the requirements asked previously. Your project is **ACCEPTED :green_circle:** and I wish you the best of luck in your next projects :+1: 

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
 You can also consider:
 
- [  **_Optional_** ] Your delete button is not being appended to the page. Kindly add that.

 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-27 20:48 UTC, merged